baseurl = "https://yushuangqi.com"
languageCode = "zh"
title = "虞双齐Golang开发" 
pygmentsuseclasses = false
PygmentsCodeFences = true
pygmentsstyle = "friendly"
uglyURLs = true
metaDataFormat = "YAML"
disqusShortname = "yushuangqi" 
publishdir = "public"

[params]
  #备案号，配置后网页底部将显示链接到备案系统
  beian = "粤ICP备14032560号-4"
  description= "虞双齐Golang语言独立开发专家-虞双齐的个人博客"

[author]
  description = "开源爱好者，Golang开发独立咨询顾问。为国内客户提供Golang开发、技术实战、架构等咨询服务。"
  name = "虞双齐"
  title= "Golang开发独立开发专家"
  # 140*140头像
  aboutme_avatar = "http://static.yushuangqi.com/assets/touxiang.jpg?imageView2/1/w/140/h/140/q/96"
  # 高清原始头像
  aboutme_height = "http://static.yushuangqi.com/assets/touxiang.jpg"
  email ="devysq@gmail.com"
  qq = "535252640"
  weibo = "234665601"
  github = "ysqi"


[taxonomies]
    tag = "tags"
    topic = "topics"

[permalinks]
	blog = "/blog/:year/:slug.html"
	top = "/:filename/"
  resource = "/resource/:title.html"
