baseurl = "https://yushuangqi.com"
languageCode = "zh"
title = "虞双齐的博客" 
pygmentsuseclasses = false
PygmentsCodeFences = true
pygmentsstyle = "friendly"
uglyURLs = true
metaDataFormat = "YAML"
disqusShortname = "yushuangqi" 
publishdir = "public"


[params]
  #备案号，配置后网页底部将显示链接到备案系统
  beian = "粤ICP备14032560号-4"
  description= "Go语言,Golang开发,SRE运维实践,全栈开发-虞双齐的个人博客"
  enableDiscuss = true

[author]
  description = "一名全栈开发工程师，#热爱编程、#工具控、#爱读书、#宅男"
  name = "虞双齐"
  title= "全栈开发"
  # 140*140头像
  aboutme_avatar = "https://static.yushuangqi.com/assets/touxiang.jpg?imageView2/1/w/140/h/140/q/96"
  # 高清原始头像
  aboutme_height = "https://static.yushuangqi.com/assets/touxiang.jpg"
  email ="ysqi@yushuangqi.com"
  qq = "460857340"
  weibo = "234665601"
  github = "ysqi"
  weixinID = "gh_d6d47893a828"
  zhihu="_ysqi"


[taxonomies]
    tag = "tags"
    topic = "topics"

[permalinks]
	blog = "/blog/:year/:slug.html"
	top = "/:slug.html"
  resource = "/resource/:title.html"  
 